/*
MySQL Data Transfer
Source Host: localhost
Source Database: satellietkanaal
Target Host: localhost
Target Database: satellietkanaal
Date: 18-3-2013 10:39:19
*/

SET FOREIGN_KEY_CHECKS=0;
-- ----------------------------
-- Table structure for kanalen
-- ----------------------------
CREATE TABLE `kanalen` (
  `nr` varchar(255) DEFAULT NULL,
  `naam` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

-- ----------------------------
-- Records 
-- ----------------------------
INSERT INTO `kanalen` VALUES ('nr', 'naam');
INSERT INTO `kanalen` VALUES ('1', 'NED1');
INSERT INTO `kanalen` VALUES ('2', 'NED2');
INSERT INTO `kanalen` VALUES ('3', 'NED3');
INSERT INTO `kanalen` VALUES ('4', 'RTL4');
INSERT INTO `kanalen` VALUES ('5', 'RTL5');
INSERT INTO `kanalen` VALUES ('6', 'SBS6');
INSERT INTO `kanalen` VALUES ('7', 'NET5');
INSERT INTO `kanalen` VALUES ('8', 'V8/Fox Kids');
INSERT INTO `kanalen` VALUES ('9', 'TMF');
INSERT INTO `kanalen` VALUES ('10', 'Yorin');
INSERT INTO `kanalen` VALUES ('11', 'Veronica/KNet');
INSERT INTO `kanalen` VALUES ('12', 'BVN');
INSERT INTO `kanalen` VALUES ('13', 'C+ Rood');
INSERT INTO `kanalen` VALUES ('14', 'C+ Blauw');
INSERT INTO `kanalen` VALUES ('15', 'C+16/9');
INSERT INTO `kanalen` VALUES ('16', 'Hallmark');
INSERT INTO `kanalen` VALUES ('17', 'Cartoon Network');
INSERT INTO `kanalen` VALUES ('18', 'NGC');
INSERT INTO `kanalen` VALUES ('19', 'Discovery');
INSERT INTO `kanalen` VALUES ('20', 'Animal Planet');
INSERT INTO `kanalen` VALUES ('21', 'EUROSPORT NL');
INSERT INTO `kanalen` VALUES ('22', 'EURONEWS');
INSERT INTO `kanalen` VALUES ('23', 'BBC WORLD');
INSERT INTO `kanalen` VALUES ('24', 'BBC Prime');
INSERT INTO `kanalen` VALUES ('25', 'MEZZO');
INSERT INTO `kanalen` VALUES ('26', 'VH1');
INSERT INTO `kanalen` VALUES ('27', 'VH1 Classic');
INSERT INTO `kanalen` VALUES ('28', 'MTV Base');
INSERT INTO `kanalen` VALUES ('29', 'MTV HITS');
INSERT INTO `kanalen` VALUES ('30', 'MTV Germany');
INSERT INTO `kanalen` VALUES ('31', 'MTV Pop');
INSERT INTO `kanalen` VALUES ('32', 'MTV 2.');
INSERT INTO `kanalen` VALUES ('33', 'MTV F');
INSERT INTO `kanalen` VALUES ('34', 'PREMIERE START');
INSERT INTO `kanalen` VALUES ('35', 'PREMIERE 1');
INSERT INTO `kanalen` VALUES ('36', 'PREMIERE 2');
INSERT INTO `kanalen` VALUES ('37', 'PREMIERE 3');
INSERT INTO `kanalen` VALUES ('38', 'PREMIERE 4');
INSERT INTO `kanalen` VALUES ('39', 'PREMIERE 5');
INSERT INTO `kanalen` VALUES ('40', 'PREMIERE 6');
INSERT INTO `kanalen` VALUES ('41', 'PREMIERE 7');
INSERT INTO `kanalen` VALUES ('42', 'PREMIERE NOSTALG');
INSERT INTO `kanalen` VALUES ('43', 'PREMIERE SERIE');
INSERT INTO `kanalen` VALUES ('44', 'Premiere Austria');
INSERT INTO `kanalen` VALUES ('45', 'PREM DIR.Portal');
INSERT INTO `kanalen` VALUES ('46', 'PREM.DIRECT 1');
INSERT INTO `kanalen` VALUES ('47', 'PREM.DIRECT 1+.5');
INSERT INTO `kanalen` VALUES ('48', 'PREM.DIRECT 1+1');
INSERT INTO `kanalen` VALUES ('49', 'PREM.DIRECT 2');
INSERT INTO `kanalen` VALUES ('50', 'PREM.DIRECT 2+.5');
INSERT INTO `kanalen` VALUES ('51', 'PREM.DIRECT 2+1');
INSERT INTO `kanalen` VALUES ('52', 'PREM.DIRECT 2+15');
INSERT INTO `kanalen` VALUES ('53', 'PREM.DIRECT 3');
INSERT INTO `kanalen` VALUES ('54', 'PREM.DIRECT 3+1');
INSERT INTO `kanalen` VALUES ('55', 'PREM.DIRECT 3+1');
INSERT INTO `kanalen` VALUES ('56', 'PREM.DIRECT 3+15');
INSERT INTO `kanalen` VALUES ('57', 'PREMIERE SPORT1');
INSERT INTO `kanalen` VALUES ('58', 'PREMIERE SPORT2');
INSERT INTO `kanalen` VALUES ('59', 'PREMIERE Portal');
INSERT INTO `kanalen` VALUES ('60', 'Konferenz');
INSERT INTO `kanalen` VALUES ('61', 'Spiel 1');
INSERT INTO `kanalen` VALUES ('62', 'Spiel 2');
INSERT INTO `kanalen` VALUES ('63', 'Spiel 3');
INSERT INTO `kanalen` VALUES ('64', 'Spiel 4');
INSERT INTO `kanalen` VALUES ('65', 'Spiel 5');
INSERT INTO `kanalen` VALUES ('66', 'Spiel 6');
INSERT INTO `kanalen` VALUES ('67', 'Spiel 7');
INSERT INTO `kanalen` VALUES ('68', 'Spiel 8');
INSERT INTO `kanalen` VALUES ('69', 'Info');
INSERT INTO `kanalen` VALUES ('70', 'F1-Portal');
INSERT INTO `kanalen` VALUES ('71', 'F1-SuperSignal');
INSERT INTO `kanalen` VALUES ('72', 'F1-Cockpit');
INSERT INTO `kanalen` VALUES ('73', 'F1-BoxenGasse');
INSERT INTO `kanalen` VALUES ('74', 'F1-Highlights');
INSERT INTO `kanalen` VALUES ('75', 'F1-Interaktiv');
INSERT INTO `kanalen` VALUES ('76', 'Premiere Partner');
INSERT INTO `kanalen` VALUES ('77', 'DPC Testcard');
INSERT INTO `kanalen` VALUES ('78', 'DPC Testcard');
INSERT INTO `kanalen` VALUES ('79', 'DPC Testcard');
INSERT INTO `kanalen` VALUES ('80', 'Champions TV');
INSERT INTO `kanalen` VALUES ('81', 'TV Travel Shop D');
INSERT INTO `kanalen` VALUES ('82', 'Frankensat');
INSERT INTO `kanalen` VALUES ('83', 'KRIMI &CO');
INSERT INTO `kanalen` VALUES ('84', 'DISCOVERY CHANNE');
INSERT INTO `kanalen` VALUES ('85', 'Planet');
INSERT INTO `kanalen` VALUES ('86', 'MGM');
INSERT INTO `kanalen` VALUES ('87', 'Studio Universal');
INSERT INTO `kanalen` VALUES ('88', 'Disney Ger');
INSERT INTO `kanalen` VALUES ('89', 'FoxKids Ger');
INSERT INTO `kanalen` VALUES ('90', '13th Street');
INSERT INTO `kanalen` VALUES ('91', 'Classica');
INSERT INTO `kanalen` VALUES ('92', 'Goldstar TV');
INSERT INTO `kanalen` VALUES ('93', 'Heimatkanal');
INSERT INTO `kanalen` VALUES ('94', 'Junior');
INSERT INTO `kanalen` VALUES ('95', 'God Channel 6-14');
INSERT INTO `kanalen` VALUES ('96', 'SonnenKlar TV');
INSERT INTO `kanalen` VALUES ('97', 'Tv.berlin');
INSERT INTO `kanalen` VALUES ('98', 'lastminute.de');
INSERT INTO `kanalen` VALUES ('99', 'SAT.1');
INSERT INTO `kanalen` VALUES ('100', 'SAT.1 A');
INSERT INTO `kanalen` VALUES ('101', 'SAT.1 CH');
INSERT INTO `kanalen` VALUES ('102', 'KABEL1');
INSERT INTO `kanalen` VALUES ('103', 'KABEL1 Schweiz');
INSERT INTO `kanalen` VALUES ('104', 'KABEL1 Austria');
INSERT INTO `kanalen` VALUES ('105', 'ProSieben');
INSERT INTO `kanalen` VALUES ('106', 'ProSieben Schwz');
INSERT INTO `kanalen` VALUES ('107', 'ProSieben Aust');
INSERT INTO `kanalen` VALUES ('108', 'NEUN LIVE Tele');
INSERT INTO `kanalen` VALUES ('109', 'DSF');
INSERT INTO `kanalen` VALUES ('110', 'Bloomberg TV Ger');
INSERT INTO `kanalen` VALUES ('111', 'N24');
INSERT INTO `kanalen` VALUES ('112', 'Tele 5');
INSERT INTO `kanalen` VALUES ('113', 'Home Shopping');
INSERT INTO `kanalen` VALUES ('114', 'QVC GERMANY');
INSERT INTO `kanalen` VALUES ('115', 'Liberty TV.com');
INSERT INTO `kanalen` VALUES ('116', 'Das Erste');
INSERT INTO `kanalen` VALUES ('117', 'EinsExtra');
INSERT INTO `kanalen` VALUES ('118', 'EinsMuXx');
INSERT INTO `kanalen` VALUES ('119', 'EinsFestival');
INSERT INTO `kanalen` VALUES ('120', 'ZDF');
INSERT INTO `kanalen` VALUES ('121', 'ZDFdokukanal');
INSERT INTO `kanalen` VALUES ('122', 'ZDFinfokanal');
INSERT INTO `kanalen` VALUES ('123', 'ZDFtheaterkanal');
INSERT INTO `kanalen` VALUES ('124', 'Bayerisches FS');
INSERT INTO `kanalen` VALUES ('125', 'WDR FERNSEHEN');
INSERT INTO `kanalen` VALUES ('126', 'Arte');
INSERT INTO `kanalen` VALUES ('127', 'SR Fernsehen');
INSERT INTO `kanalen` VALUES ('128', 'Hessen Fernsehen');
INSERT INTO `kanalen` VALUES ('129', 'BR-alpha');
INSERT INTO `kanalen` VALUES ('130', 'SÜDWEST BW');
INSERT INTO `kanalen` VALUES ('131', 'Phoenix');
INSERT INTO `kanalen` VALUES ('132', '3sat');
INSERT INTO `kanalen` VALUES ('133', 'KiKa');
INSERT INTO `kanalen` VALUES ('134', 'B1 Berlin');
INSERT INTO `kanalen` VALUES ('135', 'MDR FERNSEHEN');
INSERT INTO `kanalen` VALUES ('136', 'MDR S-Anhalt');
INSERT INTO `kanalen` VALUES ('137', 'MDR Sachsen');
INSERT INTO `kanalen` VALUES ('138', 'MDR Thürin');
INSERT INTO `kanalen` VALUES ('139', 'NDR Fernsehen');
INSERT INTO `kanalen` VALUES ('140', 'NDR HH');
INSERT INTO `kanalen` VALUES ('141', 'NDR NDS');
INSERT INTO `kanalen` VALUES ('142', 'NDR SH');
INSERT INTO `kanalen` VALUES ('143', 'ORB-Fernsehen');
INSERT INTO `kanalen` VALUES ('144', 'SÜDWEST RP');
INSERT INTO `kanalen` VALUES ('145', 'Ontv Regio');
INSERT INTO `kanalen` VALUES ('146', 'n-tv');
INSERT INTO `kanalen` VALUES ('147', 'CNBC');
INSERT INTO `kanalen` VALUES ('148', 'VIVA');
INSERT INTO `kanalen` VALUES ('149', 'VIVA PLUS');
INSERT INTO `kanalen` VALUES ('150', 'RTL Television');
INSERT INTO `kanalen` VALUES ('151', 'RTL2');
INSERT INTO `kanalen` VALUES ('152', 'Super RTL');
INSERT INTO `kanalen` VALUES ('153', 'RTL TELE Letzebu');
INSERT INTO `kanalen` VALUES ('154', 'RTL Shop');
INSERT INTO `kanalen` VALUES ('155', 'VOX');
INSERT INTO `kanalen` VALUES ('156', 'Motors TV');
INSERT INTO `kanalen` VALUES ('157', 'EuroNews');
INSERT INTO `kanalen` VALUES ('158', 'Eurosport D');
INSERT INTO `kanalen` VALUES ('159', 'Christiansen');
INSERT INTO `kanalen` VALUES ('160', 'TW1');
INSERT INTO `kanalen` VALUES ('161', 'ORF 1');
INSERT INTO `kanalen` VALUES ('162', 'ORF 2');
INSERT INTO `kanalen` VALUES ('163', 'ORF 2 W');
INSERT INTO `kanalen` VALUES ('164', 'ORF 2 N');
INSERT INTO `kanalen` VALUES ('165', 'ORF 2 B');
INSERT INTO `kanalen` VALUES ('166', 'ORF 2 O');
INSERT INTO `kanalen` VALUES ('167', 'ORF 2 S');
INSERT INTO `kanalen` VALUES ('168', 'ORF 2 T');
INSERT INTO `kanalen` VALUES ('169', 'ORF 2 V');
INSERT INTO `kanalen` VALUES ('170', 'ORF 2 St');
INSERT INTO `kanalen` VALUES ('171', 'ORF 2 K');
INSERT INTO `kanalen` VALUES ('172', 'CANAL+');
INSERT INTO `kanalen` VALUES ('173', 'CANAL+ BLEU');
INSERT INTO `kanalen` VALUES ('174', 'CANAL+ JAUNE');
INSERT INTO `kanalen` VALUES ('175', 'CANAL+ VERT');
INSERT INTO `kanalen` VALUES ('176', 'CANAL+ 16/9');
INSERT INTO `kanalen` VALUES ('177', 'C CINEMA PREMIER');
INSERT INTO `kanalen` VALUES ('178', 'C CINEMA EMOTION');
INSERT INTO `kanalen` VALUES ('179', 'C CINEMA FRISSON');
INSERT INTO `kanalen` VALUES ('180', 'C CINEMA CLASSIC');
INSERT INTO `kanalen` VALUES ('181', 'C CINEMA SUCCES');
INSERT INTO `kanalen` VALUES ('182', 'C CINEMA AUTEUR');
INSERT INTO `kanalen` VALUES ('183', 'C CINEMA CLASSIC');
INSERT INTO `kanalen` VALUES ('184', 'CINE BOX');
INSERT INTO `kanalen` VALUES ('185', 'CINE POLAR');
INSERT INTO `kanalen` VALUES ('186', 'CINE FX');
INSERT INTO `kanalen` VALUES ('187', 'CINE COMIC');
INSERT INTO `kanalen` VALUES ('188', 'FRANCE 2       *');
INSERT INTO `kanalen` VALUES ('189', 'FRANCE 3       *');
INSERT INTO `kanalen` VALUES ('190', 'FRANCE 5');
INSERT INTO `kanalen` VALUES ('191', 'TV 5 FBS');
INSERT INTO `kanalen` VALUES ('192', 'TV5 Europe');
INSERT INTO `kanalen` VALUES ('193', 'EUROSPORT');
INSERT INTO `kanalen` VALUES ('194', 'SPORT PLUS');
INSERT INTO `kanalen` VALUES ('195', 'ESPN CLASSIC   *');
INSERT INTO `kanalen` VALUES ('196', 'MCM');
INSERT INTO `kanalen` VALUES ('197', 'MCM 2          *');
INSERT INTO `kanalen` VALUES ('198', 'MCM AFRICA     *');
INSERT INTO `kanalen` VALUES ('199', 'TELE MELODY    *');
INSERT INTO `kanalen` VALUES ('200', 'PLANETE France');
INSERT INTO `kanalen` VALUES ('201', 'PLANETE Future');
INSERT INTO `kanalen` VALUES ('202', 'PLANETE Thalassa');
INSERT INTO `kanalen` VALUES ('203', 'TV BREIZH');
INSERT INTO `kanalen` VALUES ('204', 'TEVA           *');
INSERT INTO `kanalen` VALUES ('205', 'LCP');
INSERT INTO `kanalen` VALUES ('206', 'SEASONS');
INSERT INTO `kanalen` VALUES ('207', 'Bloomberg TV F');
INSERT INTO `kanalen` VALUES ('208', 'CANAL JIMMY');
INSERT INTO `kanalen` VALUES ('209', 'LA CHAINE METEO');
INSERT INTO `kanalen` VALUES ('210', 'i TELEVISION');
INSERT INTO `kanalen` VALUES ('211', 'CLUB TELEACHAT *');
INSERT INTO `kanalen` VALUES ('212', 'KTO');
INSERT INTO `kanalen` VALUES ('213', 'MATCH TV');
INSERT INTO `kanalen` VALUES ('214', 'Ciné Info');
INSERT INTO `kanalen` VALUES ('215', 'TMC Monte Carlo');
INSERT INTO `kanalen` VALUES ('216', 'PARIS PREMIERE');
INSERT INTO `kanalen` VALUES ('217', 'VOYAGE');
INSERT INTO `kanalen` VALUES ('218', 'LCI');
INSERT INTO `kanalen` VALUES ('219', 'CANAL J');
INSERT INTO `kanalen` VALUES ('220', 'SANTE - VIE');
INSERT INTO `kanalen` VALUES ('221', 'TiJi');
INSERT INTO `kanalen` VALUES ('222', 'NAT GEOGRAPHIC');
INSERT INTO `kanalen` VALUES ('223', 'GOURMET TV');
INSERT INTO `kanalen` VALUES ('224', 'CUISINE.TV');
INSERT INTO `kanalen` VALUES ('225', 'DISNEY CHANNEL');
INSERT INTO `kanalen` VALUES ('226', 'Disney Channel+1');
INSERT INTO `kanalen` VALUES ('227', 'Playhouse Disney');
INSERT INTO `kanalen` VALUES ('228', 'Toon Disney');
INSERT INTO `kanalen` VALUES ('229', 'EQUIDIA        *');
INSERT INTO `kanalen` VALUES ('230', 'RTL9           *');
INSERT INTO `kanalen` VALUES ('231', 'DEMAIN !');
INSERT INTO `kanalen` VALUES ('232', 'COMEDIE !');
INSERT INTO `kanalen` VALUES ('233', '13EME RUE');
INSERT INTO `kanalen` VALUES ('234', 'FOX KIDS       *');
INSERT INTO `kanalen` VALUES ('235', 'L\'EQUIPE TV');
INSERT INTO `kanalen` VALUES ('236', 'RFO SAT');
INSERT INTO `kanalen` VALUES ('237', 'GAME ONE');
INSERT INTO `kanalen` VALUES ('238', 'Chamber TV');
INSERT INTO `kanalen` VALUES ('239', 'CANALCLUB');
INSERT INTO `kanalen` VALUES ('240', 'CA TV');
INSERT INTO `kanalen` VALUES ('241', 'AB MOTEURS');
INSERT INTO `kanalen` VALUES ('242', 'AB 1');
INSERT INTO `kanalen` VALUES ('243', 'ANIMAUX        *');
INSERT INTO `kanalen` VALUES ('244', 'ENCYCLOPEDIA   *');
INSERT INTO `kanalen` VALUES ('245', 'ZIK\'/XXL');
INSERT INTO `kanalen` VALUES ('246', 'ESCALES');
INSERT INTO `kanalen` VALUES ('247', 'LaChaîneHistoir*');
INSERT INTO `kanalen` VALUES ('248', 'RFM TV');
INSERT INTO `kanalen` VALUES ('249', 'FASHION TV.COM');
INSERT INTO `kanalen` VALUES ('250', 'ACTION         *');
INSERT INTO `kanalen` VALUES ('251', 'MANGAS         *');
INSERT INTO `kanalen` VALUES ('252', 'RTM1 Europe');
INSERT INTO `kanalen` VALUES ('253', 'ESC1 - EGYPTE');
INSERT INTO `kanalen` VALUES ('254', 'TV7');
INSERT INTO `kanalen` VALUES ('255', 'Canal Algerie');
INSERT INTO `kanalen` VALUES ('256', 'Al Jazeera');
INSERT INTO `kanalen` VALUES ('257', 'RAI 1');
INSERT INTO `kanalen` VALUES ('258', 'DW-TV');
INSERT INTO `kanalen` VALUES ('259', 'RTPI');
INSERT INTO `kanalen` VALUES ('260', 'ARTE Francais');
INSERT INTO `kanalen` VALUES ('261', 'Sky News');
INSERT INTO `kanalen` VALUES ('262', 'CNN Int.');
INSERT INTO `kanalen` VALUES ('263', 'CNBC Europe');
INSERT INTO `kanalen` VALUES ('264', 'Travel');
INSERT INTO `kanalen` VALUES ('265', 'Cartoon Network');
INSERT INTO `kanalen` VALUES ('266', 'TCM');
INSERT INTO `kanalen` VALUES ('267', 'TVBS           *');
INSERT INTO `kanalen` VALUES ('268', 'Canal Canarias');
INSERT INTO `kanalen` VALUES ('269', 'TVC INT.');
INSERT INTO `kanalen` VALUES ('270', 'ANDALUCÍA TV');
INSERT INTO `kanalen` VALUES ('271', 'ETB');
INSERT INTO `kanalen` VALUES ('272', 'TM SAT/LA OTRA');
INSERT INTO `kanalen` VALUES ('273', 'TV-NIEP II');
INSERT INTO `kanalen` VALUES ('274', 'Polonia 1');
INSERT INTO `kanalen` VALUES ('275', 'Super 1/Tele 5');
INSERT INTO `kanalen` VALUES ('276', 'Tango TV');
INSERT INTO `kanalen` VALUES ('277', 'RTBF SAT');
INSERT INTO `kanalen` VALUES ('278', 'BTV 4U');
INSERT INTO `kanalen` VALUES ('279', 'LibertyTV.com');
INSERT INTO `kanalen` VALUES ('280', 'Astra Vision');
INSERT INTO `kanalen` VALUES ('281', '-------');
INSERT INTO `kanalen` VALUES ('282', 'Hotbird');
INSERT INTO `kanalen` VALUES ('283', '-------');
INSERT INTO `kanalen` VALUES ('284', 'EUROSPORT NL');
INSERT INTO `kanalen` VALUES ('285', 'Sailing Channel');
INSERT INTO `kanalen` VALUES ('286', '3 ABN/Buer TV');
INSERT INTO `kanalen` VALUES ('287', 'RTL2 AUSTRIA');
INSERT INTO `kanalen` VALUES ('288', 'RTL 2 CH');
INSERT INTO `kanalen` VALUES ('289', 'Super RTL A');
INSERT INTO `kanalen` VALUES ('290', 'Vox CH');
INSERT INTO `kanalen` VALUES ('291', 'tv.nrw');
INSERT INTO `kanalen` VALUES ('292', 'NBC');
INSERT INTO `kanalen` VALUES ('293', 'DeeJay TV');
INSERT INTO `kanalen` VALUES ('294', '102.5 HIT Ch');
INSERT INTO `kanalen` VALUES ('295', '123Sat.tv');
INSERT INTO `kanalen` VALUES ('296', 'ONYX');
INSERT INTO `kanalen` VALUES ('297', 'XXP');
INSERT INTO `kanalen` VALUES ('298', 'SF1');
INSERT INTO `kanalen` VALUES ('299', 'SF2');
INSERT INTO `kanalen` VALUES ('300', 'Sfi');
INSERT INTO `kanalen` VALUES ('301', 'TSR1');
INSERT INTO `kanalen` VALUES ('302', 'TSR2');
INSERT INTO `kanalen` VALUES ('303', 'TSI1');
INSERT INTO `kanalen` VALUES ('304', 'TSI2');
INSERT INTO `kanalen` VALUES ('305', 'SRG SSR SAT Acce');
INSERT INTO `kanalen` VALUES ('306', 'Cinéstar 1');
INSERT INTO `kanalen` VALUES ('307', 'Cinéstar 2');
INSERT INTO `kanalen` VALUES ('308', 'Cinétoile');
INSERT INTO `kanalen` VALUES ('309', 'Série Club');
INSERT INTO `kanalen` VALUES ('310', 'FUN TV');
INSERT INTO `kanalen` VALUES ('311', 'Teva');
INSERT INTO `kanalen` VALUES ('312', 'M6 Music');
INSERT INTO `kanalen` VALUES ('313', 'M6');
INSERT INTO `kanalen` VALUES ('314', 'Club Teleachat');
INSERT INTO `kanalen` VALUES ('315', 'Infosport');
INSERT INTO `kanalen` VALUES ('316', 'Eureka');
INSERT INTO `kanalen` VALUES ('317', 'Festival');
INSERT INTO `kanalen` VALUES ('318', 'HISTOIRE');
INSERT INTO `kanalen` VALUES ('319', 'Télétoon');
INSERT INTO `kanalen` VALUES ('320', 'Odyssée');
INSERT INTO `kanalen` VALUES ('321', 'RFO (21-03)');
INSERT INTO `kanalen` VALUES ('322', 'Teletoon+1');
INSERT INTO `kanalen` VALUES ('323', 'LCI');
INSERT INTO `kanalen` VALUES ('324', 'FRANCE 5');
INSERT INTO `kanalen` VALUES ('325', 'FRANCE 2');
INSERT INTO `kanalen` VALUES ('326', 'Eurosport France');
INSERT INTO `kanalen` VALUES ('327', 'FRANCE 3 Sat');
INSERT INTO `kanalen` VALUES ('328', 'Paris Premiere');
INSERT INTO `kanalen` VALUES ('329', 'Arte Francais');
INSERT INTO `kanalen` VALUES ('330', 'I>Tele');
INSERT INTO `kanalen` VALUES ('331', 'RTM1 Europe');
INSERT INTO `kanalen` VALUES ('332', 'Nice People');
INSERT INTO `kanalen` VALUES ('333', 'Equidia');
INSERT INTO `kanalen` VALUES ('334', 'ESPN Classic Fr');
INSERT INTO `kanalen` VALUES ('335', 'Cine Info');
INSERT INTO `kanalen` VALUES ('336', 'BBC PRIME');
INSERT INTO `kanalen` VALUES ('337', 'TV Breizh');
INSERT INTO `kanalen` VALUES ('338', 'La Chaine Parlem');
INSERT INTO `kanalen` VALUES ('339', 'TPS star');
INSERT INTO `kanalen` VALUES ('340', 'Cinéfaz');
INSERT INTO `kanalen` VALUES ('341', 'TF1');
INSERT INTO `kanalen` VALUES ('342', 'TFOU Promo');
INSERT INTO `kanalen` VALUES ('343', 'TF6');
INSERT INTO `kanalen` VALUES ('344', 'Meteo Express');
INSERT INTO `kanalen` VALUES ('345', 'KTO-TV Catholiqu');
INSERT INTO `kanalen` VALUES ('346', 'The God Channel');
INSERT INTO `kanalen` VALUES ('347', 'Boomerang Fr');
INSERT INTO `kanalen` VALUES ('348', 'Beur TV');
INSERT INTO `kanalen` VALUES ('349', 'RTR-Planeta');
INSERT INTO `kanalen` VALUES ('350', 'SIC Internation');
INSERT INTO `kanalen` VALUES ('351', 'TFJ');
INSERT INTO `kanalen` VALUES ('352', 'Multivision 1');
INSERT INTO `kanalen` VALUES ('353', 'Multivision 2');
INSERT INTO `kanalen` VALUES ('354', 'Multivision 3');
INSERT INTO `kanalen` VALUES ('355', 'Multivision 4');
INSERT INTO `kanalen` VALUES ('356', 'Multivision 5');
INSERT INTO `kanalen` VALUES ('357', 'Multivision 6');
INSERT INTO `kanalen` VALUES ('358', 'Multivision 7');
INSERT INTO `kanalen` VALUES ('359', 'Multiv. Promo');
INSERT INTO `kanalen` VALUES ('360', 'CHASSE&PECHE');
INSERT INTO `kanalen` VALUES ('361', 'MUSIQUE CLASSIQU');
INSERT INTO `kanalen` VALUES ('362', 'AB4 TEST');
INSERT INTO `kanalen` VALUES ('363', 'PASSIONS');
INSERT INTO `kanalen` VALUES ('364', 'CINE BOX');
INSERT INTO `kanalen` VALUES ('365', 'CINE POLAR');
INSERT INTO `kanalen` VALUES ('366', 'CINE FX');
INSERT INTO `kanalen` VALUES ('367', 'CINE COMIC');
INSERT INTO `kanalen` VALUES ('368', 'RAI1');
INSERT INTO `kanalen` VALUES ('369', 'RAI2');
INSERT INTO `kanalen` VALUES ('370', 'RAI3');
INSERT INTO `kanalen` VALUES ('371', 'RaiMed');
INSERT INTO `kanalen` VALUES ('372', 'RAIeducational');
INSERT INTO `kanalen` VALUES ('373', 'RAINews24');
INSERT INTO `kanalen` VALUES ('374', 'RAINettunoSAT1');
INSERT INTO `kanalen` VALUES ('375', 'RAINettunoSAT2');
INSERT INTO `kanalen` VALUES ('376', 'RAISPORTSAT');
INSERT INTO `kanalen` VALUES ('377', 'RAILAB');
INSERT INTO `kanalen` VALUES ('378', ' I1');
INSERT INTO `kanalen` VALUES ('379', ' C5');
INSERT INTO `kanalen` VALUES ('380', ' R4');
INSERT INTO `kanalen` VALUES ('381', 'Canale Lavoro');
INSERT INTO `kanalen` VALUES ('382', 'CAMERA DEPUTATI');
INSERT INTO `kanalen` VALUES ('383', 'TELEPACE');
INSERT INTO `kanalen` VALUES ('384', 'SAT2000');
INSERT INTO `kanalen` VALUES ('385', 'MILAN CH.');
INSERT INTO `kanalen` VALUES ('386', 'INTER CH.');
INSERT INTO `kanalen` VALUES ('387', 'Stream1');
INSERT INTO `kanalen` VALUES ('388', 'Stream 2');
INSERT INTO `kanalen` VALUES ('389', 'Stream News Ch');
INSERT INTO `kanalen` VALUES ('390', 'Cinema Stream');
INSERT INTO `kanalen` VALUES ('391', 'Cine Movie');
INSERT INTO `kanalen` VALUES ('392', 'Prima Spettacoli');
INSERT INTO `kanalen` VALUES ('393', 'PrimafilaCine 1a');
INSERT INTO `kanalen` VALUES ('394', 'PrimafilaCine 1b');
INSERT INTO `kanalen` VALUES ('395', 'PrimafilaCine 1c');
INSERT INTO `kanalen` VALUES ('396', 'PrimafilaCine 1d');
INSERT INTO `kanalen` VALUES ('397', 'PrimafilaCine 2a');
INSERT INTO `kanalen` VALUES ('398', 'PrimafilaCine 2b');
INSERT INTO `kanalen` VALUES ('399', 'PrimafilaCine 2c');
INSERT INTO `kanalen` VALUES ('400', 'PrimafilaCine 2d');
INSERT INTO `kanalen` VALUES ('401', 'PrimafilaCine 3a');
INSERT INTO `kanalen` VALUES ('402', 'PrimafilaCine 3b');
INSERT INTO `kanalen` VALUES ('403', 'PrimafilaCine 4a');
INSERT INTO `kanalen` VALUES ('404', 'PrimafilaCine 4b');
INSERT INTO `kanalen` VALUES ('405', 'PrimafilaCine 5a');
INSERT INTO `kanalen` VALUES ('406', 'PrimafilaCine 5b');
INSERT INTO `kanalen` VALUES ('407', 'PrimafilaCine 6a');
INSERT INTO `kanalen` VALUES ('408', 'PrimafilaCine 6b');
INSERT INTO `kanalen` VALUES ('409', 'Calcio Stream');
INSERT INTO `kanalen` VALUES ('410', 'Campionato St 1');
INSERT INTO `kanalen` VALUES ('411', 'Campionato St 2');
INSERT INTO `kanalen` VALUES ('412', 'Campionato St 3');
INSERT INTO `kanalen` VALUES ('413', 'Campionato St 4');
INSERT INTO `kanalen` VALUES ('414', 'Campionato St 5');
INSERT INTO `kanalen` VALUES ('415', 'CFN/CNBC Italia');
INSERT INTO `kanalen` VALUES ('416', 'Duel TV');
INSERT INTO `kanalen` VALUES ('417', 'Comedy Life');
INSERT INTO `kanalen` VALUES ('418', 'Fox Kids Italia');
INSERT INTO `kanalen` VALUES ('419', 'Nat.Geographic');
INSERT INTO `kanalen` VALUES ('420', 'Roma Channel');
INSERT INTO `kanalen` VALUES ('421', 'Sport Stream F');
INSERT INTO `kanalen` VALUES ('422', 'Canale Viaggi');
INSERT INTO `kanalen` VALUES ('423', 'Il Canale Info');
INSERT INTO `kanalen` VALUES ('424', 'SNAI Sat');
INSERT INTO `kanalen` VALUES ('425', 'Studio Universal');
INSERT INTO `kanalen` VALUES ('426', 'Cult Network It');
INSERT INTO `kanalen` VALUES ('427', 'TV L');
INSERT INTO `kanalen` VALUES ('428', 'HSE Italia');
INSERT INTO `kanalen` VALUES ('429', 'MT Channel');
INSERT INTO `kanalen` VALUES ('430', 'Stream Verde');
INSERT INTO `kanalen` VALUES ('431', 'Fox News Channel');
INSERT INTO `kanalen` VALUES ('432', 'C. Milagro');
INSERT INTO `kanalen` VALUES ('433', 'HB Channel/VTV4');
INSERT INTO `kanalen` VALUES ('434', 'HB Channel 2');
INSERT INTO `kanalen` VALUES ('435', 'TV MODA');
INSERT INTO `kanalen` VALUES ('436', 'ARM 1');
INSERT INTO `kanalen` VALUES ('437', 'Coming Soon TV');
INSERT INTO `kanalen` VALUES ('438', 'SaluteBenessere');
INSERT INTO `kanalen` VALUES ('439', 'SICILIA INTERNAT');
INSERT INTO `kanalen` VALUES ('440', 'SARDEGNA UNO');
INSERT INTO `kanalen` VALUES ('441', 'VIDEOLINA');
INSERT INTO `kanalen` VALUES ('442', 'NAPOLI INT.');
INSERT INTO `kanalen` VALUES ('443', 'MAGIC');
INSERT INTO `kanalen` VALUES ('444', 'COUNTDOWN');
INSERT INTO `kanalen` VALUES ('445', 'Studio Europa');
INSERT INTO `kanalen` VALUES ('446', 'Telemarket');
INSERT INTO `kanalen` VALUES ('447', 'GAME NETWORK');
INSERT INTO `kanalen` VALUES ('448', 'Chat Game TV');
INSERT INTO `kanalen` VALUES ('449', 'Teve Pika');
INSERT INTO `kanalen` VALUES ('450', 'GAY.TV');
INSERT INTO `kanalen` VALUES ('451', 'Caspio Net');
INSERT INTO `kanalen` VALUES ('452', 'Duna TV');
INSERT INTO `kanalen` VALUES ('453', 'Tiziana Sat');
INSERT INTO `kanalen` VALUES ('454', 'Tv7 Tunesia');
INSERT INTO `kanalen` VALUES ('455', 'NOELLO SAT');
INSERT INTO `kanalen` VALUES ('456', 'Mediolanum Chann');
INSERT INTO `kanalen` VALUES ('457', '24ore.tv');
INSERT INTO `kanalen` VALUES ('458', 'Telesierra');
INSERT INTO `kanalen` VALUES ('459', 'Italiasat/RCT');
INSERT INTO `kanalen` VALUES ('460', 'Digitaly');
INSERT INTO `kanalen` VALUES ('461', 'EURO MEDITERRANE');
INSERT INTO `kanalen` VALUES ('462', 'HCN');
INSERT INTO `kanalen` VALUES ('463', 'HIGH TV');
INSERT INTO `kanalen` VALUES ('464', 'CNL New Live Ch');
INSERT INTO `kanalen` VALUES ('465', 'Q-Channel');
INSERT INTO `kanalen` VALUES ('466', 'Telecampione');
INSERT INTO `kanalen` VALUES ('467', 'Odeon TV');
INSERT INTO `kanalen` VALUES ('468', 'Motors TV');
INSERT INTO `kanalen` VALUES ('469', 'BT Broadcast');
INSERT INTO `kanalen` VALUES ('470', 'CTV');
INSERT INTO `kanalen` VALUES ('471', 'Jaya TV India');
INSERT INTO `kanalen` VALUES ('472', 'TBNE');
INSERT INTO `kanalen` VALUES ('473', 'Videolina');
INSERT INTO `kanalen` VALUES ('474', 'Telegenova');
INSERT INTO `kanalen` VALUES ('475', 'CNES-Toulouse');
INSERT INTO `kanalen` VALUES ('476', 'TVE INTERNACIONA');
INSERT INTO `kanalen` VALUES ('477', 'CANAL 24 HORAS');
INSERT INTO `kanalen` VALUES ('478', 'ERT SAT');
INSERT INTO `kanalen` VALUES ('479', 'NET');
INSERT INTO `kanalen` VALUES ('480', 'EXTRA');
INSERT INTO `kanalen` VALUES ('481', 'TRIAL');
INSERT INTO `kanalen` VALUES ('482', 'TV MAGIC');
INSERT INTO `kanalen` VALUES ('483', 'MKTV');
INSERT INTO `kanalen` VALUES ('484', 'BALKANIA TV');
INSERT INTO `kanalen` VALUES ('485', 'TVN');
INSERT INTO `kanalen` VALUES ('486', 'TVN 24');
INSERT INTO `kanalen` VALUES ('487', 'TVN 7 Siedem');
INSERT INTO `kanalen` VALUES ('488', 'TVN Feeds');
INSERT INTO `kanalen` VALUES ('489', 'TV POLONIA');
INSERT INTO `kanalen` VALUES ('490', 'Tele 5 Poland');
INSERT INTO `kanalen` VALUES ('491', 'VIVA polska');
INSERT INTO `kanalen` VALUES ('492', 'HRT-TV1');
INSERT INTO `kanalen` VALUES ('493', 'HRT-TV2');
INSERT INTO `kanalen` VALUES ('494', 'HRT-TV3');
INSERT INTO `kanalen` VALUES ('495', 'SLO-TV1');
INSERT INTO `kanalen` VALUES ('496', 'SLO-TV2');
INSERT INTO `kanalen` VALUES ('497', 'Tv Bulgaria');
INSERT INTO `kanalen` VALUES ('498', 'TV ROMANIA');
INSERT INTO `kanalen` VALUES ('499', 'RTB INTERNATIONA');
INSERT INTO `kanalen` VALUES ('500', 'RTS SAT');
INSERT INTO `kanalen` VALUES ('501', 'RTV MONTENEGRO');
INSERT INTO `kanalen` VALUES ('502', 'Khalifa');
INSERT INTO `kanalen` VALUES ('503', 'KHALIFA NEWS');
INSERT INTO `kanalen` VALUES ('504', 'Kurdsat');
INSERT INTO `kanalen` VALUES ('505', 'Kurdistan TV');
INSERT INTO `kanalen` VALUES ('506', 'Tizianasat');
INSERT INTO `kanalen` VALUES ('507', 'BBC World');
INSERT INTO `kanalen` VALUES ('508', 'Euronews');
INSERT INTO `kanalen` VALUES ('509', 'ANN');
INSERT INTO `kanalen` VALUES ('510', 'NTV Int.-HTB');
INSERT INTO `kanalen` VALUES ('511', 'NTV Int.-Nashe K');
INSERT INTO `kanalen` VALUES ('512', 'NTV Int.-Detsky');
INSERT INTO `kanalen` VALUES ('513', 'STUDIO N.Y. Feed');
INSERT INTO `kanalen` VALUES ('514', 'ART Europe');
INSERT INTO `kanalen` VALUES ('515', 'ART Teenz Europe');
INSERT INTO `kanalen` VALUES ('516', 'ART Aflam');
INSERT INTO `kanalen` VALUES ('517', 'ART Music');
INSERT INTO `kanalen` VALUES ('518', 'ART Sport');
INSERT INTO `kanalen` VALUES ('519', 'NILE Drama');
INSERT INTO `kanalen` VALUES ('520', 'NILE Variety');
INSERT INTO `kanalen` VALUES ('521', 'NILE TV');
INSERT INTO `kanalen` VALUES ('522', 'NILE NEWS');
INSERT INTO `kanalen` VALUES ('523', 'AL JAZEERA');
INSERT INTO `kanalen` VALUES ('524', '2M Maroc');
INSERT INTO `kanalen` VALUES ('525', 'MA 3');
INSERT INTO `kanalen` VALUES ('526', 'Arab Test Card');
INSERT INTO `kanalen` VALUES ('527', 'Canal Algérie');
INSERT INTO `kanalen` VALUES ('528', 'Sharjah');
INSERT INTO `kanalen` VALUES ('529', 'Qatar');
INSERT INTO `kanalen` VALUES ('530', 'Saudi 1');
INSERT INTO `kanalen` VALUES ('531', 'Kuwait');
INSERT INTO `kanalen` VALUES ('532', 'Libya');
INSERT INTO `kanalen` VALUES ('533', 'Sudan');
INSERT INTO `kanalen` VALUES ('534', 'Oman');
INSERT INTO `kanalen` VALUES ('535', 'Abu Dhabi TV');
INSERT INTO `kanalen` VALUES ('536', 'Iraq');
INSERT INTO `kanalen` VALUES ('537', 'IQRA');
INSERT INTO `kanalen` VALUES ('538', 'Al manar');
INSERT INTO `kanalen` VALUES ('539', 'Jordan-tv');
INSERT INTO `kanalen` VALUES ('540', 'Al-alam');
INSERT INTO `kanalen` VALUES ('541', 'ESC');
INSERT INTO `kanalen` VALUES ('542', 'UBN/Asb');
INSERT INTO `kanalen` VALUES ('543', 'Al Arabiyah');
INSERT INTO `kanalen` VALUES ('544', 'MBC');
INSERT INTO `kanalen` VALUES ('545', 'IRIB1 PER');
INSERT INTO `kanalen` VALUES ('546', 'IRIB2 PER');
INSERT INTO `kanalen` VALUES ('547', 'IRIB1 ENG');
INSERT INTO `kanalen` VALUES ('548', 'IRIB2 ENG');
INSERT INTO `kanalen` VALUES ('549', 'IRINN');
INSERT INTO `kanalen` VALUES ('550', 'SAHAR1');
INSERT INTO `kanalen` VALUES ('551', 'SAHAR2');
INSERT INTO `kanalen` VALUES ('552', 'SAT 7');
INSERT INTO `kanalen` VALUES ('553', 'SYRIAN TV');
INSERT INTO `kanalen` VALUES ('554', 'CFI Peco Pro');
INSERT INTO `kanalen` VALUES ('555', 'Fashion Tv');
INSERT INTO `kanalen` VALUES ('556', 'Tamil TV Netw');
INSERT INTO `kanalen` VALUES ('557', 'AJARA TV');
INSERT INTO `kanalen` VALUES ('558', 'Thai TV5');
INSERT INTO `kanalen` VALUES ('559', 'JSTV Promo');
INSERT INTO `kanalen` VALUES ('560', 'CCTV4');
INSERT INTO `kanalen` VALUES ('561', 'CCTV9');
INSERT INTO `kanalen` VALUES ('562', 'Asianet');
INSERT INTO `kanalen` VALUES ('563', 'MOU.2');
INSERT INTO `kanalen` VALUES ('564', 'EbS');
INSERT INTO `kanalen` VALUES ('565', 'CALABRIASAT');
INSERT INTO `kanalen` VALUES ('566', 'GBC');
INSERT INTO `kanalen` VALUES ('567', 'E-TV');
INSERT INTO `kanalen` VALUES ('568', 'K-TV');
INSERT INTO `kanalen` VALUES ('569', '06 TV');
INSERT INTO `kanalen` VALUES ('570', 'TRT Tamil Ozhi');
INSERT INTO `kanalen` VALUES ('571', 'Ceylon TV');
INSERT INTO `kanalen` VALUES ('572', '---');
INSERT INTO `kanalen` VALUES ('573', 'SEX Astra/Hotb.');
INSERT INTO `kanalen` VALUES ('574', '---');
INSERT INTO `kanalen` VALUES ('575', 'PREMIERE ERO.1');
INSERT INTO `kanalen` VALUES ('576', 'PREMIERE ERO.2');
INSERT INTO `kanalen` VALUES ('577', 'PREMIERE ERO.3');
INSERT INTO `kanalen` VALUES ('578', 'PREMIERE ERO.4');
INSERT INTO `kanalen` VALUES ('579', 'Beate_Ushe TV');
INSERT INTO `kanalen` VALUES ('580', 'FreeX-tv (Astra)');
INSERT INTO `kanalen` VALUES ('581', 'FreeX-tv (Hotb)');
INSERT INTO `kanalen` VALUES ('582', 'Multi Ero 1');
INSERT INTO `kanalen` VALUES ('583', 'Multi Ero 2');
INSERT INTO `kanalen` VALUES ('584', 'Multi Ero 3');
INSERT INTO `kanalen` VALUES ('585', 'XXL Club 1');
INSERT INTO `kanalen` VALUES ('586', 'XXL Club 2');
INSERT INTO `kanalen` VALUES ('587', 'XXL Club 3');
INSERT INTO `kanalen` VALUES ('588', 'XXL Club 4');
INSERT INTO `kanalen` VALUES ('589', 'XXL Hotbird');
INSERT INTO `kanalen` VALUES ('590', 'XXL Astra');
INSERT INTO `kanalen` VALUES ('591', 'X-ZONE');
INSERT INTO `kanalen` VALUES ('592', 'Satisfaction');
INSERT INTO `kanalen` VALUES ('593', 'Sex-View');
INSERT INTO `kanalen` VALUES ('594', 'Sex-View Plus');
INSERT INTO `kanalen` VALUES ('595', 'Ultra Blue TV');
INSERT INTO `kanalen` VALUES ('596', 'Spice Platinum');
INSERT INTO `kanalen` VALUES ('597', 'Blu Line TV');
INSERT INTO `kanalen` VALUES ('598', 'Pleasure TV');
INSERT INTO `kanalen` VALUES ('599', 'Sexy Sat');
INSERT INTO `kanalen` VALUES ('600', 'Lunapark');
INSERT INTO `kanalen` VALUES ('1112', 'Astra Radio');
INSERT INTO `kanalen` VALUES ('1113', 'Radio 1');
INSERT INTO `kanalen` VALUES ('1114', 'Radio 2');
INSERT INTO `kanalen` VALUES ('1115', 'Radio 3FM');
INSERT INTO `kanalen` VALUES ('1116', 'Radio 4');
INSERT INTO `kanalen` VALUES ('1117', '747AM');
INSERT INTO `kanalen` VALUES ('1118', 'RTL RADIO');
INSERT INTO `kanalen` VALUES ('1119', 'Sky Radio');
INSERT INTO `kanalen` VALUES ('1120', 'Radio 10 FM');
INSERT INTO `kanalen` VALUES ('1121', 'Radio538');
INSERT INTO `kanalen` VALUES ('1122', 'Yorin FM');
INSERT INTO `kanalen` VALUES ('1123', 'KINK FM');
INSERT INTO `kanalen` VALUES ('1124', 'Veronica Radio');
INSERT INTO `kanalen` VALUES ('1125', 'ClassicFM');
INSERT INTO `kanalen` VALUES ('1126', 'RVi1 (VRT)');
INSERT INTO `kanalen` VALUES ('1127', 'RVi2 (VRT)');
INSERT INTO `kanalen` VALUES ('1128', 'MM + sel.audio');
INSERT INTO `kanalen` VALUES ('1129', 'RNW1');
INSERT INTO `kanalen` VALUES ('1130', 'RNW2');
INSERT INTO `kanalen` VALUES ('1131', 'RNW3 Promo');
INSERT INTO `kanalen` VALUES ('1132', 'Concertzender');
INSERT INTO `kanalen` VALUES ('1133', 'FRANCE MUSIQUES');
INSERT INTO `kanalen` VALUES ('1134', 'FIP');
INSERT INTO `kanalen` VALUES ('1135', 'France INFO');
INSERT INTO `kanalen` VALUES ('1136', 'France INTER');
INSERT INTO `kanalen` VALUES ('1137', 'France BLEU');
INSERT INTO `kanalen` VALUES ('1138', 'RFI INT');
INSERT INTO `kanalen` VALUES ('1139', 'RADIO CLASSIQUE');
INSERT INTO `kanalen` VALUES ('1140', 'EUROPE 1');
INSERT INTO `kanalen` VALUES ('1141', 'RMC');
INSERT INTO `kanalen` VALUES ('1142', 'RTL');
INSERT INTO `kanalen` VALUES ('1143', 'RIRE ET CHANSONS');
INSERT INTO `kanalen` VALUES ('1144', 'SUD RADIO');
INSERT INTO `kanalen` VALUES ('1145', 'M FM');
INSERT INTO `kanalen` VALUES ('1146', 'TSF');
INSERT INTO `kanalen` VALUES ('1147', 'NOSTALGIE');
INSERT INTO `kanalen` VALUES ('1148', 'BFM');
INSERT INTO `kanalen` VALUES ('1149', 'PARIS JAZZ');
INSERT INTO `kanalen` VALUES ('1150', 'NRJ');
INSERT INTO `kanalen` VALUES ('1151', 'EUROPE 2');
INSERT INTO `kanalen` VALUES ('1152', 'RTL 2');
INSERT INTO `kanalen` VALUES ('1153', 'SKYROCK');
INSERT INTO `kanalen` VALUES ('1154', 'FUN RADIO');
INSERT INTO `kanalen` VALUES ('1155', 'LE MOUV');
INSERT INTO `kanalen` VALUES ('1156', 'RADIO NOVA');
INSERT INTO `kanalen` VALUES ('1157', 'RADIO FG');
INSERT INTO `kanalen` VALUES ('1158', 'VIBRATION');
INSERT INTO `kanalen` VALUES ('1159', 'CONTACT FM');
INSERT INTO `kanalen` VALUES ('1160', 'RADIO LATINA');
INSERT INTO `kanalen` VALUES ('1161', 'RFM');
INSERT INTO `kanalen` VALUES ('1162', 'CHERIE FM');
INSERT INTO `kanalen` VALUES ('1163', 'ALOUETTE');
INSERT INTO `kanalen` VALUES ('1164', 'VOLTAGE');
INSERT INTO `kanalen` VALUES ('1165', 'OUI FM');
INSERT INTO `kanalen` VALUES ('1166', 'ADO');
INSERT INTO `kanalen` VALUES ('1167', 'COULEUR 3');
INSERT INTO `kanalen` VALUES ('1168', 'RFI MUSIQUE');
INSERT INTO `kanalen` VALUES ('1169', 'RADIO NOTRE-DAME');
INSERT INTO `kanalen` VALUES ('1170', 'RADIO ALPHA');
INSERT INTO `kanalen` VALUES ('1171', 'RCJ / SHALOM');
INSERT INTO `kanalen` VALUES ('1172', 'BEUR FM');
INSERT INTO `kanalen` VALUES ('1173', 'MEDIA TROPICAL');
INSERT INTO `kanalen` VALUES ('1174', 'AFRICA N1');
INSERT INTO `kanalen` VALUES ('1175', 'MEDI 1');
INSERT INTO `kanalen` VALUES ('1176', 'France CULTURE');
INSERT INTO `kanalen` VALUES ('1177', 'WRN');
INSERT INTO `kanalen` VALUES ('1178', 'JUMP');
INSERT INTO `kanalen` VALUES ('1179', 'Fritz');
INSERT INTO `kanalen` VALUES ('1180', 'SPUTNIK');
INSERT INTO `kanalen` VALUES ('1181', 'Bayern 1');
INSERT INTO `kanalen` VALUES ('1182', 'Bayern 4 Klassik');
INSERT INTO `kanalen` VALUES ('1183', 'B5 aktuell');
INSERT INTO `kanalen` VALUES ('1184', 'NordwestRadio');
INSERT INTO `kanalen` VALUES ('1185', 'NDR 4 Info');
INSERT INTO `kanalen` VALUES ('1186', 'SR 1');
INSERT INTO `kanalen` VALUES ('1187', 'hr-klassik');
INSERT INTO `kanalen` VALUES ('1188', 'hr2');
INSERT INTO `kanalen` VALUES ('1189', 'HR XXL');
INSERT INTO `kanalen` VALUES ('1190', 'hr-chronos');
INSERT INTO `kanalen` VALUES ('1191', 'DLF-Köln');
INSERT INTO `kanalen` VALUES ('1192', 'DLR-Berlin');
INSERT INTO `kanalen` VALUES ('1193', 'Radio 3');
INSERT INTO `kanalen` VALUES ('1194', 'RADIOmultikulti');
INSERT INTO `kanalen` VALUES ('1195', 'MDR info');
INSERT INTO `kanalen` VALUES ('1196', 'MDR KULTUR');
INSERT INTO `kanalen` VALUES ('1197', 'SWR2');
INSERT INTO `kanalen` VALUES ('1198', 'WDR 3');
INSERT INTO `kanalen` VALUES ('1199', 'WDR Radio 5');
INSERT INTO `kanalen` VALUES ('1200', 'Österreich 1');
INSERT INTO `kanalen` VALUES ('1201', 'OE1');
INSERT INTO `kanalen` VALUES ('1202', 'OE 2 W');
INSERT INTO `kanalen` VALUES ('1203', 'OE 2 N');
INSERT INTO `kanalen` VALUES ('1204', 'OE 2 B');
INSERT INTO `kanalen` VALUES ('1205', 'OE 2 O');
INSERT INTO `kanalen` VALUES ('1206', 'OE 2 S');
INSERT INTO `kanalen` VALUES ('1207', 'OE 2 T');
INSERT INTO `kanalen` VALUES ('1208', 'OE 2 V');
INSERT INTO `kanalen` VALUES ('1209', 'OE 2 St');
INSERT INTO `kanalen` VALUES ('1210', 'OE 2 K');
INSERT INTO `kanalen` VALUES ('1211', 'OE 3');
INSERT INTO `kanalen` VALUES ('1212', 'FM4');
INSERT INTO `kanalen` VALUES ('1213', 'ROIWIEN');
INSERT INTO `kanalen` VALUES ('1214', 'ROI-SAC');
